### ISSUE TITLE
pssession isn't working with msdns provider

### ISSUE THREAD

**Issue by split-and-join** [StackExchange/dnscontrol#1104]
Executing the following locally on a DNS server returns all records..
`dnscontrol get-zones --format=js msdns MSDNS <domainName>`

When creds.json is setup it prints the INFO message, but does not throw any errors, and prints a default domain record with no addresses.

I am running these versions:
dnscontrol v3.7.0-dev
go version go1.16.2 windows/amd64
Windows Server 2016

**Comment by tlimoncelli** [comment]
Hi there!

Yes, pssession doesn't work.  I need to remove it from the documentation until it is ready.

Can you use the "dnsserver" option instead?

Tom

**Comment by split-and-join** [comment]
I was able to use the dnsserver option remotely. I had both defined in the `creds.json` and believe it defaulted to pssession.

I am relatively new to golang, but wouldn't mind taking a look at why this is failing. If you have any points in the code where you think it might be failing I can give it a try.

**Comment by tlimoncelli** [comment]
The good news is that I found a bug... the pssession variable wasn't being stored anywhere.  I fixed that in https://github.com/StackExchange/dnscontrol/pull/1105

The bad news is that my test environment for Windows only has 1 machine.

If you want to try https://github.com/StackExchange/dnscontrol/pull/1105 to see if it fixes things, that'd be awesome.  The code that deals with this is all in `dnscontrol/providers/msdns/powershell.go`

**Comment by split-and-join** [comment]
I tried to execute the new branch, and that doesn't seem to solve the problem..

I was debugging the code and everything looked right until I got to line 41 of [session.go](https://github.com/bhendo/go-powershell/blob/219e7fb4e41e15c1a8f68c7f082c4c6df96d6362/middleware/session.go#L41) 

```go
return s.upstream.Execute(fmt.Sprintf("Invoke-Command -Session $%s -Script {%s}", s.name,cmd))
```
I realize that is not your project, but it seems like there is some underlying issue going on with that module. The PowerShell generated to execute is valid. I could execute it in a regular PowerShell session, but this function just doesn't seem to return anything to stdout.

**Comment by tlimoncelli** [comment]
Interesting!

If you think it is a bug in powershell and/or the module, could you make a repo case?   I know a few powershell MVPs that might be able to help out.

**Comment by tlimoncelli** [comment]
I wonder if this helps: https://stackoverflow.com/questions/50809752/golang-invoking-powershell-exe-always-returns-ascii-characters

I wonder if we should switch to something like https://github.com/KnicKnic/go-powershell (sadly I think it requires cgo, which I'd rather avoid).

**Comment by split-and-join** [comment]
Looks like the bhendo/go-powershell repo isn't actively maintained, and they won't fix.

I was looking at the KnicKnic repo, and didn't see where they are using cgo. I saw a c dll they were loading from https://github.com/KnicKnic/native-powershell, but did not sure if that is the same.

**Comment by tlimoncelli** [comment]
I may have misspoke.  I saw the c dll and assumed they were using cgo.

**Comment by split-and-join** [comment]
Okay, so did some more digging and found that when using the pssession the results were being saved to the remote computer instead of the local system where dnscontrol is running. Here is the powershell it is executing.

```powershell
"Invoke-Command -Session $goSess5973deea5db00875 -Scriptblock {Get-DnsServerResourceRecord -ZoneName "example.com" | ConvertTo-Json -depth 4 > C:\Users\user\AppData\Local\Temp\zonerecords.609499399.json} "
```

Believe this impacts the diff operation for seeing what records need to be added/removed, as well as the initial get-zones issue I was having. Not sure if there is a better way of redirecting this output to localhost.

Believe this would work in `generatePSZoneDump` to prevent the remote file save.
```go	
if dnsserver != "" {
	fmt.Fprintf(&b, ` > %s`, filename)
}
```
Then in `GetDNSZoneRecords` stdout could save a local file.
```go
if stdout != "" {
  if dnsserver != "" {
	  fmt.Printf("STDOUT = %q\n", stdout)
  } else {
	  ioutil.WriteFile(tmpfile.Name(), []byte(stdout), 0)
  }
}
```
Not 100% that this would solve everything, but I know that it saves the file and then reads it without error, but think that there is something still needed for Unmarshaling.

**Comment by tlimoncelli** [comment]
The redirect looks very promising!  Yes, the remote machine saving data locally would certainly explain the behavior.

Busy day today but I'll try this soon!

**Comment by split-and-join** [comment]
Take your time! Appreciate the work you are doing on this project.

**Comment by split-and-join** [comment]
@tlimoncelli I cobbled together this branch with a few changes.. It is mostly working, but I believe that the PSRemote values that are returned aren't being typed correctly. 

https://github.com/StackExchange/dnscontrol/compare/master...split-and-join:update-msdns-pssession

**Comment by split-and-join** [comment]
I actually think I got it to work for remote and local sessions on my current branch. These are the different cases I have tried 

- Using only dnsserver in creds.json
- Using only pssession in creds.json
- Using pssession, psusername, pspassword in creds.json

And they all do the expected of returning output.

**Comment by tlimoncelli** [comment]
Wow!  I'm really excited about this!  I'll have time to look at this over the weekend.

Question for ya:  How's the performance?   I seem to recall it was the Json conversion at the end that was slow when I did this, but I also think I was having some kind of system problem at the time.

**Comment by tlimoncelli** [comment]
Cool cool.  A little slower is to be expected. The problem I had must have been something different.

Thanks for the PR!    I'm glad this feature now works!

**Comment by split-and-join** [comment]
Sweet Deal! Happy to contribute! Will look at maybe testing cross platform powershell for this resource next.
