### ISSUE TITLE
CHORE: Upgrade to latest goreleaser

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#2469]
goreleaser v1.19 dropped support for the legacy nfpm formats

v1.18 reports:

```
  • setting defaults
      • DEPRECATED: `nfpms.replacements` should not be used anymore, check https://goreleaser.com/deprecations#nfpmsreplacements for more info
      • DEPRECATED: `nfpms.replacements` should not be used anymore, check https://goreleaser.com/deprecations#nfpmsreplacements for more info
```

As a workaround, we've pinned goreleaser to v1.8 (https://github.com/StackExchange/dnscontrol/pull/2467) (But that doesn't seem to be working.)

What needs to be done:

* Update .goreleaser to use the the newer format, not `nfpms.replacements`. 
 
Acceptance criteria:

* Builds work
* Builds produce packages with all the same names as before. See [v4,1,1](https://github.com/StackExchange/dnscontrol/releases/tag/v4.1.1) as an example list of filenames. Alternatively, use new names if there is a better name convention we should comply with.

**Comment by tlimoncelli** [comment]
CC @jauderho  I could use a little help here.  Debugging Goreleaser is a mystery to me.  You seem to understand it better than I do.  I hate to be a pain but would you have time to take a look at this?  I'd super appreciate it!

**Comment by jauderho** [comment]
Looking at 

* https://goreleaser.com/deprecations/#nfpmsreplacements
* https://github.com/smallstep/certificates/issues/768

It looks like substituting for `file_name_template: "{{ .ConventionalFileName }}"`, should make things work (at least for now). 

I've got a different repo that I can do some testing with when I get some time.

**Comment by TomOnTime** [comment]
@SignalRichard I know you're busy but would you have a moment to look into this?  I failed to get this working by pinning to the old version of goreleaser (https://github.com/StackExchange/dnscontrol/pull/2467).  The best solution is to fix things so that we're using the newest goreleaser.

**Comment by SignalRichard** [comment]
> @SignalRichard I know you're busy but would you have a moment to look into this? I failed to get this working by pinning to the old version of goreleaser (#2467). The best solution is to fix things so that we're using the newest goreleaser.

Will try and take a look as soon as I can!

**Comment by SignalRichard** [comment]
@TomOnTime - I pushed a change to the branch from #2467 to update the nfpms for the `file_name_template` and removed the replacements.  Hopefully this fixes the issue

**Comment by tlimoncelli** [comment]
@SignalRichard Sadly the build is still having a problem.  See https://github.com/StackExchange/dnscontrol/actions/runs/5763331720/job/15624905377


```
 > [run 2/4] RUN --mount=type=cache,target=/var/cache/apk     apk update     && apk add tzdata ca-certificates     && update-ca-certificates:
0.241 exec /bin/sh: exec format error
------
Dockerfile:8
--------------------
   7 |     # - ca-certificates: Needed for https to work properly
   8 | >>> RUN --mount=type=cache,target=/var/cache/apk \
   9 | >>>     apk update \
  10 | >>>     && apk add tzdata ca-certificates \
  11 | >>>     && update-ca-certificates
  12 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apk update     && apk add tzdata ca-certificates     && update-ca-certificates" did not complete successfully: exit code: 1
```

**Comment by SignalRichard** [comment]
@TomOnTime Taking a look at the build error, will hopefully have a fix

**Comment by tlimoncelli** [comment]
Yes, it looks like it worked.  I'll clean up the PR and merge it.  If you don't hear from me, assume that was the fix.

I'm surprised that "run" doesn't permit "&&".  I figured they passed the entire line to system(), not exec() (or equivalents).

**Comment by TomOnTime** [comment]
@SignalRichard That seems to have fixed it but now we have another issue. Can you take a look at https://github.com/StackExchange/dnscontrol/actions/runs/5800350486 ? I am not sure what the problem is.

**Comment by SignalRichard** [comment]
> @SignalRichard That seems to have fixed it but now we have another issue. Can you take a look at https://github.com/StackExchange/dnscontrol/actions/runs/5800350486 ? I am not sure what the problem is.

Yep, will take a look!

**Comment by SignalRichard** [comment]
> @SignalRichard That seems to have fixed it but now we have another issue. Can you take a look at https://github.com/StackExchange/dnscontrol/actions/runs/5800350486 ? I am not sure what the problem is.

So, GitHub Actions has several contexts, but not all of them are available to the workflow run when it is triggered by a fork which include `variables` and `secrets`.  What is happening here is the PR triggers the workflow to run but it runs in the context of the user's fork and uses any variables and secrets defined in their forked repository.  In this case there are no variables and only the GitHub actions token available in secrets.  This is done to protect against potentially dangerous PRs where the attacker could modify a workflow file and expose secret values.  This means when the workflow attempts to figure out which integration tests to run by checking which provider variables and/or secrets are available it comes up with nothing. 

Some reading on this:
* https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
* https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
* https://stackoverflow.com/questions/73866908/github-actions-main-repository-secret-not-picked-up-from-pull-request-build
* https://github.com/orgs/community/discussions/44322

What should probably be done in this case is to split the integration tests part of the workflow off so that it doesn't cause a build failure and ensure that the integration tests are run before a release can be made (also when a push is made to the default branch to give visibility as soon as possible).  This is of course not as ideal since we can't check the integration tests during a PR from a fork to ensure that everything will keep working.
