### ISSUE TITLE
BIND provider no longer updates serial in latest release (v0.2.4)

### ISSUE THREAD

**Issue by techdad** [StackExchange/dnscontrol#284]
To reproduce, create a test zone with 2 or 3 records and a using a `defualt_soa` template with the BIND provider.

Then, download from https://github.com/StackExchange/dnscontrol/releases the binaries for both release v0.2.3 and v0.2.4.

When running the same zone through 0.2.3, the serial is incremented as expected and set to current date if starting from 0. However, when running through 0.2.4, after the initial zone creation, the serial never changes, not matter if records are added or removed.

**Comment by tlimoncelli** [comment]
Can you try the code on this branch? It should fix it.

**Comment by techdad** [comment]
Thanks for working on this.
Doesn't seem to fix it yet though, sorry about that.

**Comment by tlimoncelli** [comment]
Could you help me reproduce the bug?  Here's a tar file of what I did to reproduce the bug.

[repro.tar.gz](https://github.com/StackExchange/dnscontrol/files/1571528/repro.tar.gz)

When you run repro.sh, look at the lines that start with `@@@@@@@`. They should increment the serial  number.

```
$ bash repro.sh 
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
 (7 records)

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 1: SERIAL NUMBER: 1
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
CREATE A three.example.tld 1.2.3.4 ttl=300

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 2: SERIAL NUMBER: 2017121901
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
CREATE A more.example.tld 1.2.3.4 ttl=300

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 3: SERIAL NUMBER: 2017121902
```

**Comment by techdad** [comment]
With pleasure. Thanks again for looking at this.

I've edited repro.sh and added one line, just before the for loop:

```
$CMD version
```

...and first changed only `CMD=`, to the full, absolute path of  the older 0.2.3 release, downloaded from the github releases as a tarball, and extracted. All looks good as expected:

```
% bash repro.sh
dnscontrol 0.2.3 ("f2098de61108df8f6a32924e3ee3ff6352c200b0") built 19 Oct 17 17:01 +04
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
 (7 records)

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 1: SERIAL NUMBER: 1
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
CREATE A three.example.tld 1.2.3.4 ttl=300

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 2: SERIAL NUMBER: 2017121901
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
CREATE A more.example.tld 1.2.3.4 ttl=300

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 3: SERIAL NUMBER: 2017121902
```

Next, I've edited `CMD=` once more, pointing to the binary build by doing:

```
git clone https://github.com/StackExchange/dnscontrol.git
cd dnscontrol
go run build/build.go
```
(the change seems to be merged into master as far as I can see - I did this previously by checkout of the branch)

So finally:

```
% bash repro.sh
dnscontrol 0.2.4 ("ed2b34d473c65650437ebc22637cb4856655757b") built 19 Dec 17 16:50 +04
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
 (7 records)

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 1: SERIAL NUMBER: 1
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
CREATE A three.example.tld 1.2.3.4 ttl=300

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 2: SERIAL NUMBER: 1
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
CREATE A more.example.tld 1.2.3.4 ttl=300

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 3: SERIAL NUMBER: 1
```

In case it helps, go installd with `homebrew` on macOS:

```
% sw_vers                                                                           127 ↵
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1114
```
```
% go version
go version go1.9.2 darwin/amd64
```

**Comment by tlimoncelli** [comment]
Yes, I merged the change into master due to my incompetence at git.... i mean... I saw it was working for SO so I merged it in :-)

Anyway...

I'm still unable to repro this.  Is there any chance that your repro.sh is running the wrong binary?

```
$ cat repro.sh 
#!/bin/bash

rm -rf dnscontrol
git clone https://github.com/StackExchange/dnscontrol.git
go run dnscontrol/build/build.go
find . -name dnscontrol\* -ls
CMD=./dnscontrol-Darwin
echo CMD="$CMD"

rm -rf zones
mkdir -p zones

set -e

for i in 1 2 3 ; do
   cp data$i.json dnsconfig.js
  $CMD push
  SN=$(grep 'IN SOA'  zones/example.tld.zone   | awk '{print $6 }')
  echo "@@@@@@@@@@@@@@ TEST $i: SERIAL NUMBER: $SN"
done

$ bash repro.sh 
Cloning into 'dnscontrol'...
remote: Counting objects: 4896, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 4896 (delta 9), reused 16 (delta 5), pack-reused 4865
Receiving objects: 100% (4896/4896), 5.95 MiB | 11.04 MiB/s, done.
Resolving deltas: 100% (2351/2351), done.
2017/12/19 09:05:09 Building dnscontrol-Linux
2017/12/19 09:05:32 Building dnscontrol.exe
2017/12/19 09:05:54 Building dnscontrol-Darwin
8593271923    31896 -rwxr-x---    1 tlimoncelli      staff            15693312 Dec 19 09:05 ./dnscontrol.exe
8593268896        0 drwxr-x---   22 tlimoncelli      staff                 704 Dec 19 09:05 ./dnscontrol
8593271054    31504 -rwxr-x---    1 tlimoncelli      staff            15496192 Dec 19 09:05 ./dnscontrol-Linux
8593271934    33920 -rwxr-x---    1 tlimoncelli      staff            17363340 Dec 19 09:05 ./dnscontrol-Darwin
CMD=./dnscontrol-Darwin
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
 (7 records)

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 1: SERIAL NUMBER: 1
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
CREATE A three.example.tld 1.2.3.4 ttl=300

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 2: SERIAL NUMBER: 2017121901
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
CREATE A more.example.tld 1.2.3.4 ttl=300

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 3: SERIAL NUMBER: 2017121902

$ 
```

**Comment by techdad** [comment]
Nope, not wrong binary:

```
% cat repro.sh                                                                                        130 ↵
#!/bin/bash

rm -rf dnscontrol
git clone https://github.com/StackExchange/dnscontrol.git
go run dnscontrol/build/build.go
find . -name dnscontrol\* -ls
CMD=./dnscontrol-Darwin
echo CMD="$CMD"

rm -rf zones
mkdir -p zones

set -e

for i in 1 2 3 ; do
   cp data$i.json dnsconfig.js
  $CMD push
  SN=$(grep 'IN SOA'  zones/example.tld.zone   | awk '{print $6 }')
  echo "@@@@@@@@@@@@@@ TEST $i: SERIAL NUMBER: $SN"
done


% bash repro.sh
Cloning into 'dnscontrol'...
remote: Counting objects: 4896, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 4896 (delta 9), reused 16 (delta 5), pack-reused 4865
Receiving objects: 100% (4896/4896), 5.95 MiB | 1.16 MiB/s, done.
Resolving deltas: 100% (2351/2351), done.
2017/12/19 22:00:33 Building dnscontrol-Linux
2017/12/19 22:00:54 Building dnscontrol.exe
2017/12/19 22:01:15 Building dnscontrol-Darwin
50811514        0 drwxr-xr-x   22 daniel           staff                 748 19 Dec 22:00 ./dnscontrol
50814970    33920 -rwxr-xr-x    1 daniel           staff            17363340 19 Dec 22:01 ./dnscontrol-Darwin
50813669    30272 -rwxr-xr-x    1 daniel           staff            15496192 19 Dec 22:00 ./dnscontrol-Linux
50814536    30656 -rwxr-xr-x    1 daniel           staff            15692288 19 Dec 22:01 ./dnscontrol.exe
CMD=./dnscontrol-Darwin
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
 (7 records)

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 1: SERIAL NUMBER: 1
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
CREATE A three.example.tld 1.2.3.4 ttl=300

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 2: SERIAL NUMBER: 1
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.tld
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.tld
CREATE A more.example.tld 1.2.3.4 ttl=300

CREATING ZONEFILE: zones/example.tld.zone
SUCCESS!
----- Registrar: ThirdParty...0 corrections
Done. 1 corrections.
@@@@@@@@@@@@@@ TEST 3: SERIAL NUMBER: 1
```

But so this makes me think it's something on this laptop. And so, next step is to try this on some other host. I tried a CentOS 7 host I have access to, that didn't even have golang yet.

And I hit a problem with the build. Excuse my ignorance with building go stuff, but his is what I get:

```
‹master› % go run build/build.go
2017/12/19 22:41:45 Building dnscontrol-Linux
can't load package: package github.com/StackExchange/dnscontrol: cannot find package "github.com/StackExchange/dnscontrol" in any of:
	/usr/lib/golang/src/github.com/StackExchange/dnscontrol (from $GOROOT)
	/home/daniel/go/src/github.com/StackExchange/dnscontrol (from $GOPATH)
2017/12/19 22:41:45 exit status 1
exit status 1
```

... Do I need to do a `go get ...` first?

**Comment by techdad** [comment]
OK! Progress 😄 

Re-reading my comment above, I had a thought... I'm not very familiar with building go binaries from source. But it seems like on this case, the build looks for the source, not in `$PWD`, but rather (also?) in `$GOPATH/src/`..

And on the laptop where I'm testing this, I do still have the previous 0.2.4 (and broken) binary, installed with `go get -u github.com/StackExchange/dnscontrol`.

As the fix in `ed2b34d`, *is* merged into the master, I thought why not try re-get and see. I therefore re-ran `go get -u github.com/StackExchange/dnscontrol` again since that commit, and lo and behold! It works!

Both the binary now updated in `$GOPATH`, and **also** re-running `repro.sh` again. All work 100%!

So **thank you**, the fix *did* fix it!

(PS: A line added to the README.md on how to do a clean source build may be a useful future addtion 😉 )

**Comment by tlimoncelli** [comment]
Interesting!

Due to the weird way that Go works with packages, I think it will build better if you copy  repro.sh and data*.json  to ~/src/github.com/StackExchange and run it there.  That should put all the modules in the right place.  I'm not sure how it worked for you without that.

**Comment by techdad** [comment]
Yep! This works!

**Comment by tlimoncelli** [comment]
w000t!

**Comment by techdad** [comment]
Thanks for all the time troubleshooting this :)

**Comment by tlimoncelli** [comment]
Glad to help!
