### ISSUE TITLE
Multiple strings in TXT not supported by GCLOUD

### ISSUE THREAD

**Issue by igg** [StackExchange/dnscontrol#407]
Using either of these syntaxes with GCLOUD results in an error:
```
TXT("google._domainkey", DKIM("very long string"))
```
or
```
TXT("google._domainkey", ['some string','some other string'])
```
The error reported is
 ```
ERROR: TXT records with multiple strings (label google._domainkey domain: example.com) not supported by gcloud
```
gcloud does support multiple strings in TXT entries, as discussed in this [stackoverflow question](https://stackoverflow.com/questions/36688278/unable-to-setup-dkim-txt-value-as-dns-record).

N.B.: In the DKIM syntax above, the string has to be longer than 256 bytes in order to be split into multiple strings.

**Comment by igg** [comment]
Not sure it even qualifies as a workaround, but it is possible to get Google to generate shorter DKIM keys, and these do work.

**Comment by tlimoncelli** [comment]
This is fixed in https://github.com/StackExchange/dnscontrol/pull/415

Some time between when GCLOUD support was added and now it started working. Either Google added support, or the refactoring we did earlier this year fixed whatever was broken on our side.

Easiest bug fix evah!

**Comment by jeanpaulgalea** [comment]
Hi @tlimoncelli,

Sorry to keep pestering you about this issue...

While the fix does allow from longer DKIM keys, the following still doesn't work on GCLOUD and R53 providers:
```
TXT("google._domainkey", "very long string")
```

The errors are:
```
FAILURE! googleapi: Error 400: Invalid value for 'entity.change.additions[0].rrdata[0]': '"txt value redacted"', invalid
```
```
FAILURE! InvalidChangeBatch: Invalid Resource Record: FATAL problem: CharacterStringTooLong (Value is too long) encountered with '"txt value redacted"'
	status code: 400, request id: e6053875-d85d-11e8-a0f0-3d51f9144f47
```

However, using the syntax as suggested by @igg, `DKIM("string")` or `["max 255", "etc"]` does work for both providers.

My question then is, wouldn't it be better if TXT strings are automatically split up in chunks of 255? The user wouldn't have to care about TXT lengths and simply use one syntax.

FYI, `DKIM()` helper doesn't seem to be documented. Happy to try and provide a patch for this, unless you decide to throw away the helper in favor of automatically splitting up the string.

Thanks!

**Comment by tlimoncelli** [comment]
I'm generally in favor of this. I just need a little time to think about it.

In the meanwhile, I've filed https://github.com/StackExchange/dnscontrol/issues/418 because the input validation should be done earlier.

I'm rather ignorant about how TXT with multiple strings is used by other systems:  Are there applications that would want the split to be on spaces instead of the 256th byte?

Would this violate the principle that "functions named after a RTYPE should be the simple version" rule?  i.e. should there be TXTsplit() for autosplitting and TXT() should retain the current behavior?  Or should there be TXTshort() that restricts to 1 string and TXT() does autosplit?

Tom
