### ISSUE TITLE
Support Gandi as a registrar

### ISSUE THREAD

**Issue by bfirsh** [StackExchange/dnscontrol#87]
It is claimed to be supported, but doesn't seem to actually be implemented. See also #85.

**Comment by tlimoncelli** [comment]
I've added this to the [list of requests](https://stackexchange.github.io/dnscontrol/provider-list). If someone would like to volunteer to implement this, please re-open this issue. 

Advice on how to write a provider is documented [here](https://stackexchange.github.io/dnscontrol/writing-providers). Also, speak up in this issue and someone will get back to you asap.

**Comment by philhug** [comment]
@tlimoncelli ok, I prepared registrar support for gandi.

There is one external dependency which needs to be merged first.
https://github.com/prasmussen/gandi-api/pull/13

**Comment by philhug** [comment]
See #274

**Comment by philhug** [comment]
@captncraig could you reopen this issue?

**Comment by philhug** [comment]
@captncraig and closed again :)

**Comment by tlimoncelli** [comment]
Fixed in https://github.com/StackExchange/dnscontrol/commit/f6ce421fdd2306fc778fd13b1346781542d6f864

**Comment by tresni** [comment]
@tlimoncelli still shows up as a requested provider even though it's supported
